jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-spring-plugin
      version: 2.0.0
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-plantuml-report-plugin
      version: 2.0.1
    - group-id: de.kontext-e.jqassistant.plugin
      artifact-id: jqassistant.plugin.git
      version: 1.12.0
    - group-id: de.kontext-e.jqassistant.plugin
      artifact-id: jqassistant.plugin.jacoco
      version: 1.12.0

  scan:
    include:
      files:
        - ../.git
        - target/site/jacoco

    properties:
      jqassistant.plugin.jacoco.filename: jacoco.xml

  concepts:
    - common:*